"""Add driver_id to driver_patti

Revision ID: 2b5c7c22720d
Revises: 
Create Date: 2025-08-05 17:09:21.041828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b5c7c22720d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('vehicle_number', sa.String(length=50), nullable=True),
    sa.Column('village', sa.String(length=100), nullable=True),
    sa.Column('default_rate', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('farmer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('village', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('lot_by_farmer')
    op.drop_table('buyers')
    op.drop_table('farmers')
    op.drop_table('drivers')
    with op.batch_alter_table('driver_patti', schema=None) as batch_op:
        batch_op.add_column(sa.Column('driver_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('date', sa.String(length=20), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('transport_rate',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('total_transport_cost',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'driver', ['driver_id'], ['id'])
        batch_op.drop_column('transporter_village')
        batch_op.drop_column('driver_name')
        batch_op.drop_column('vehicle_number')

    with op.batch_alter_table('lot_info', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('lot_number',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('transport_rate',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('transport_amount',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('date',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'farmer', ['farmer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lot_info', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'farmers', ['farmer_id'], ['id'])
        batch_op.alter_column('date',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('transport_amount',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('transport_rate',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('lot_number',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('driver_patti', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehicle_number', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('driver_name', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('transporter_village', sa.TEXT(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('total_transport_cost',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('transport_rate',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.drop_column('date')
        batch_op.drop_column('driver_id')

    op.create_table('drivers',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('vehicle_number', sa.TEXT(), nullable=True),
    sa.Column('village', sa.TEXT(), nullable=True),
    sa.Column('default_rate', sa.REAL(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('farmers',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('village', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('buyers',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('firm_name', sa.TEXT(), nullable=True),
    sa.Column('contact', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lot_by_farmer',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('driver_patti_id', sa.INTEGER(), nullable=True),
    sa.Column('lot_number', sa.TEXT(), nullable=True),
    sa.Column('farmer_name', sa.TEXT(), nullable=True),
    sa.Column('farmer_village', sa.TEXT(), nullable=True),
    sa.Column('vehicle_number', sa.TEXT(), nullable=True),
    sa.Column('jk_boxes', sa.INTEGER(), nullable=True),
    sa.Column('other_boxes', sa.INTEGER(), nullable=True),
    sa.Column('transport_rate', sa.REAL(), nullable=True),
    sa.Column('total_boxes', sa.INTEGER(), nullable=True),
    sa.Column('transport_amount', sa.REAL(), nullable=True),
    sa.ForeignKeyConstraint(['driver_patti_id'], ['driver_patti.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('farmer')
    op.drop_table('driver')
    # ### end Alembic commands ###
